# Generated by Django 2.0.7 on 2018-07-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='path',
            field=models.CharField(max_length=500),
        ),
    ]
