# Generated by Django 2.0.7 on 2018-07-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0002_auto_20180727_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='lineno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
