# Generated by Django 2.0.7 on 2018-07-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0003_comment_lineno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='path',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
