# Generated by Django 2.0.7 on 2018-07-28 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0004_auto_20180727_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
