# Generated by Django 2.0.7 on 2018-07-28 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0009_projectdirectory_parentproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdirectory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='projectdirectory',
            name='parentproject',
        ),
        migrations.RemoveField(
            model_name='projectfile',
            name='parentproject',
        ),
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(to='annotate.ProjectFile'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='filetype',
            field=models.CharField(choices=[('f', 'file'), ('d', 'directory')], default='f', max_length=1),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotate.ProjectFile'),
        ),
        migrations.DeleteModel(
            name='ProjectDirectory',
        ),
    ]
