# Generated by Django 2.0.7 on 2018-07-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0010_auto_20180728_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
