# Generated by Django 2.0.7 on 2018-07-28 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0011_auto_20180728_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='files',
        ),
        migrations.RemoveField(
            model_name='projectfile',
            name='parent',
        ),
        migrations.AddField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='annotate.Project'),
            preserve_default=False,
        ),
    ]
