# Generated by Django 2.0.7 on 2018-07-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0012_auto_20180728_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcomment',
            name='projectfile',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='snippet',
        ),
        migrations.AddField(
            model_name='comment',
            name='projectfile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='annotate.ProjectFile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProjectComment',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
