# Generated by Django 2.0.7 on 2018-07-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0013_auto_20180728_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='download_source',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='downloaded',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
