# Generated by Django 2.0.7 on 2018-08-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0014_auto_20180728_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
