# Generated by Django 2.0.7 on 2018-08-07 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0016_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotate.Directory')),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('text', models.TextField(blank=True)),
                ('downloaded', models.BooleanField()),
                ('download_source', models.URLField(blank=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotate.Directory')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectfile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='projectfile',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProjectFile',
        ),
        migrations.AddField(
            model_name='snippet',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotate.Project'),
        ),
        migrations.AddField(
            model_name='directory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotate.Project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='snippet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='annotate.Snippet'),
            preserve_default=False,
        ),
    ]
