# Generated by Django 2.0.7 on 2018-08-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0019_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.CharField(choices=[('GH', 'GitHub'), ('CM', 'Custom')], default='CM', max_length=2),
        ),
    ]
