# Generated by Django 2.0.7 on 2018-08-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0020_project_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
