# Generated by Django 2.0.7 on 2018-08-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0021_auto_20180811_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='directory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='parent',
        ),
        migrations.AddField(
            model_name='directory',
            name='path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
