# Generated by Django 2.0.7 on 2018-08-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0022_auto_20180813_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='name',
        ),
    ]
