# Generated by Django 2.0.7 on 2018-08-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0023_auto_20180813_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='path',
            new_name='fullpath',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='path',
            new_name='fullpath',
        ),
        migrations.AddField(
            model_name='directory',
            name='dirpath',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directory',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='dirpath',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
